// SPDX-License-Identifier: MIT
//
// Copyright (c) 2020-2021 Antonio Niño Díaz

// Example of how to set priorities to backgrounds and sprites.

#include <ugba/ugba.h>

#include "ball_green.h" // Autogenerated from ball_green.png
#include "ball_red.h"   // Autogenerated from ball_red.png
#include "city.h" // Autogenerated from city.png

// This defines the tile index where the data of the ball is loaded in tile VRAM
#define BALL_RED_TILES_BASE         (16)
#define BALL_GREEN_TILES_BASE       (64)

// This is the palette index to be used for the sprite. There are 16 palettes of
// 16 colors each available.
#define BALL_RED_PALETTE            (2)
#define BALL_GREEN_PALETTE          (6)

// Background definitions
#define CITY_MAP_PALETTE            (0)
#define CITY_TILES_BASE             MEM_BG_TILES_BLOCK_ADDR(0)
#define CITY_MAP_BASE               MEM_BG_MAP_BLOCK_ADDR(8)

void load_sprites(void)
{
    // Load the palettes

    VRAM_OBJPalette16Copy(ball_redPal, ball_redPalLen,
                          BALL_RED_PALETTE);
    VRAM_OBJPalette16Copy(ball_greenPal, ball_greenPalLen,
                          BALL_GREEN_PALETTE);

    // Load the tiles

    VRAM_OBJTiles16Copy(ball_redTiles, ball_redTilesLen,
                        BALL_RED_TILES_BASE);
    VRAM_OBJTiles16Copy(ball_greenTiles, ball_greenTilesLen,
                        BALL_GREEN_TILES_BASE);
}

void load_background(void)
{
    // Load the palette
    VRAM_BGPalette16Copy(cityPal, cityPalLen, CITY_MAP_PALETTE);

    // Load the tiles
    SWI_CpuSet_Copy16(cityTiles, (void *)CITY_TILES_BASE, cityTilesLen);

    // Load the map
    SWI_CpuSet_Copy16(cityMap, (void *)CITY_MAP_BASE, cityMapLen);
}

int main(int argc, char *argv[])
{
    UGBA_Init(&argc, &argv);

    // Enable interrupts. This is needed for SWI_VBlankIntrWait() to work.
    IRQ_Enable(IRQ_VBLANK);

    // Load graphics
    // -------------

    load_background();
    load_sprites();

    // Set object attributes
    // ---------------------

    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 3; i++)
        {
            int index = j * 3 + i;
            int x = 4 + i * 40;
            int y = 4 + j * 40;

            if ((i ^ j) & 1)
            {
                OBJ_RegularInit(index, x, y, OBJ_SIZE_32x32, OBJ_16_COLORS,
                                BALL_RED_PALETTE, BALL_RED_TILES_BASE);
            }
            else
            {
                OBJ_RegularInit(index, x, y, OBJ_SIZE_32x32, OBJ_16_COLORS,
                                BALL_GREEN_PALETTE, BALL_GREEN_TILES_BASE);
            }
        }
    }

    // Setup first background
    // ----------------------

    BG_RegularInit(2, BG_REGULAR_512x512, BG_16_COLORS,
                   CITY_TILES_BASE, CITY_MAP_BASE);

    // Setup second background (text console)
    // --------------------------------------

    CON_InitDefault();

    int max_i = GBA_SCREEN_W / 8;
    int max_j = GBA_SCREEN_H / 8;

    for (int j = 0; j < max_j; j++)
    {
        for (int i = 0; i < max_i; i++)
        {
            // Skip last position to not trigger a newline
            if ((i == (max_i - 1)) && (j == (max_j - 1)))
                continue;

            char str[2] = { 0 };
            str[0] = 'A' + i + j;
            CON_Print(str);
        }
    }

    // Set display configuration
    // -------------------------

    // Set the display to mode 0 so that all backgrounds are in regular mode
    DISP_ModeSet(0);

    // Turn on backgrounds 0 and 2, and sprites.
    DISP_LayersEnable(1, 0, 1, 0, 1);

    // Enable 1D mapping. Check "8.2.1. The sprite mapping mode" in the
    // following link for more information:
    //     https://www.coranac.com/tonc/text/regobj.htm#sec-tiles
    DISP_Object1DMappingEnable(1);

    // Setup windows
    // -------------

    WIN_Win0SizeSet(50, 190, 50, 110);
    WIN_Win1SizeSet(10, 230, 10, 150);

    WIN_Win0LayersSet(WININ0_BG2_ENABLE | WININ0_OBJ_ENABLE);
    WIN_Win1LayersSet(WININ1_BG0_ENABLE | WININ1_OBJ_ENABLE);
    WIN_WinOutLayersSet(0);

    DISP_WindowsEnable(1, 1, 0);

    while (1)
        SWI_VBlankIntrWait();
}
