// SPDX-License-Identifier: MIT
//
// Copyright (c) 2020 Antonio Niño Díaz

// Example that shows how to use the HBLANK interrupt to create visual effects.

#include <ugba/ugba.h>

#include "city.h" // Autogenerated from city.png

#define CITY_MAP_PALETTE    (0)
#define CITY_TILES_BASE     MEM_BG_TILES_BLOCK_ADDR(0)
#define CITY_MAP_BASE       MEM_BG_MAP_BLOCK_ADDR(8)

void load_bg(void)
{
    // Load the palette
    VRAM_BGPalette16Copy(cityPal, cityPalLen, CITY_MAP_PALETTE);

    // Load the tiles
    SWI_CpuSet_Copy16(cityTiles, (void *)CITY_TILES_BASE, cityTilesLen);

    // Load the map
    SWI_CpuSet_Copy16(cityMap, (void *)CITY_MAP_BASE, cityMapLen);

    // Setup background
    BG_RegularInit(0, BG_REGULAR_512x512, BG_16_COLORS,
                   CITY_TILES_BASE, CITY_MAP_BASE);
}

int x = 80, y = 120;
uint16_t horizontal_offsets[160];

void fill_array(void)
{
    for (int i = 0; i < 160; i++)
        horizontal_offsets[i] = x + ((i & 16) ? (i & 15) : 15 - (i & 15));
}

void vbl_handler(void)
{
    // The first HBL interrupt happens after line 0 is drawn. It is needed set
    // the first offset during the VBL.
    REG_BG0HOFS = horizontal_offsets[0];
}

void hbl_handler(void)
{
    REG_BG0HOFS = horizontal_offsets[REG_VCOUNT + 1];
}

int main(int argc, char *argv[])
{
    UGBA_Init(&argc, &argv);

    load_bg();
    fill_array();
    REG_BG0VOFS = y;

    // Enable interrupts
    IRQ_SetHandler(IRQ_VBLANK, vbl_handler);
    IRQ_SetHandler(IRQ_HBLANK, hbl_handler);
    IRQ_Enable(IRQ_VBLANK);
    IRQ_Enable(IRQ_HBLANK);

    // Set the display to mode 0 so that all backgrounds are in regular mode,
    // and turn on background 0.
    REG_DISPCNT = DISPCNT_BG_MODE(0) | DISPCNT_BG0_ENABLE;

    while (1)
    {
        SWI_VBlankIntrWait();

        KEYS_Update();

        uint16_t keys = KEYS_Held();

        if (keys & KEY_UP)
            y--;
        else if (keys & KEY_DOWN)
            y++;

        if (keys & KEY_RIGHT)
            x++;
        else if (keys & KEY_LEFT)
            x--;

        fill_array();
        REG_BG0VOFS = y;
    }
}
