# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020-2021 Antonio Niño Díaz

EXAMPLE_PATH := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

LIBUGBA := $(EXAMPLE_PATH)/../../../libugba

include $(EXAMPLE_PATH)/../../../examples/common.mk
