// SPDX-License-Identifier: MIT
//
// Copyright (c) 2020-2021 Antonio Niño Díaz

// Example of how to enable the mosaic effect.

#include <ugba/ugba.h>

#include "ball_green.h" // Autogenerated from ball_green.png
#include "ball_red.h"   // Autogenerated from ball_red.png
#include "city.h" // Autogenerated from city.png

// This defines the tile index where the data of the ball is loaded in tile VRAM
#define BALL_RED_TILES_BASE         (16)
#define BALL_GREEN_TILES_BASE       (64)

// This is the palette index to be used for the sprite. There are 16 palettes of
// 16 colors each available.
#define BALL_RED_PALETTE            (2)
#define BALL_GREEN_PALETTE          (6)

// Background definitions
#define CITY_MAP_PALETTE            (0)
#define CITY_TILES_BASE             MEM_BG_TILES_BLOCK_ADDR(0)
#define CITY_MAP_BASE               MEM_BG_MAP_BLOCK_ADDR(8)

void load_sprites(void)
{
    // Load the palettes

    VRAM_OBJPalette16Copy(ball_redPal, ball_redPalLen,
                          BALL_RED_PALETTE);
    VRAM_OBJPalette16Copy(ball_greenPal, ball_greenPalLen,
                          BALL_GREEN_PALETTE);

    // Load the tiles

    VRAM_OBJTiles16Copy(ball_redTiles, ball_redTilesLen,
                        BALL_RED_TILES_BASE);
    VRAM_OBJTiles16Copy(ball_greenTiles, ball_greenTilesLen,
                        BALL_GREEN_TILES_BASE);
}

void load_background(void)
{
    // Load the palette
    VRAM_BGPalette16Copy(cityPal, cityPalLen, CITY_MAP_PALETTE);

    // Load the tiles
    SWI_CpuSet_Copy16(cityTiles, (void *)CITY_TILES_BASE, cityTilesLen);

    // Load the map
    SWI_CpuSet_Copy16(cityMap, (void *)CITY_MAP_BASE, cityMapLen);
}

int main(int argc, char *argv[])
{
    UGBA_Init(&argc, &argv);

    // Enable interrupts. This is needed for SWI_VBlankIntrWait() to work.
    IRQ_Enable(IRQ_VBLANK);

    // Load graphics
    // -------------

    load_background();
    load_sprites();

    // Set object attributes
    // ---------------------

    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 3; i++)
        {
            int index = j * 3 + i;
            int x = 4 + i * 40;
            int y = 4 + j * 40;

            if ((i ^ j) & 1)
            {
                OBJ_RegularInit(index, x, y, OBJ_SIZE_32x32, OBJ_16_COLORS,
                                BALL_RED_PALETTE, BALL_RED_TILES_BASE);
            }
            else
            {
                OBJ_RegularInit(index, x, y, OBJ_SIZE_32x32, OBJ_16_COLORS,
                                BALL_GREEN_PALETTE, BALL_GREEN_TILES_BASE);
            }

            OBJ_MosaicSet(index, 1);
        }
    }

    // Setup background
    // ----------------

    BG_RegularInit(0, BG_REGULAR_512x512, BG_16_COLORS,
                   CITY_TILES_BASE, CITY_MAP_BASE);

    BG_MosaicEnable(0, 1);

    int x = 80, y = 120;
    BG_RegularScrollSet(0, x, y);

    // Set display configuration
    // -------------------------

    // Set the display to mode 0 so that all backgrounds are in regular mode,
    // and turn on background 0 and sprites.
    DISP_ModeSet(0);
    DISP_LayersEnable(1, 0, 0, 0, 1);

    // Enable 1D mapping. Check "8.2.1. The sprite mapping mode" in the
    // following link for more information:
    //     https://www.coranac.com/tonc/text/regobj.htm#sec-tiles
    DISP_Object1DMappingEnable(1);

    DISP_MosaicSet(3, 6, 4, 2);

    while (1)
    {
        SWI_VBlankIntrWait();

        KEYS_Update();

        uint16_t keys = KEYS_Held();

        BG_RegularScrollGet(0, &x, &y);

        if (keys & KEY_UP)
            y--;
        else if (keys & KEY_DOWN)
            y++;

        if (keys & KEY_RIGHT)
            x++;
        else if (keys & KEY_LEFT)
            x--;

        BG_RegularScrollSet(0, x, y);
    }
}
