# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 Antonio Niño Díaz

EXAMPLE_PATH := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

LIBUGBA := $(EXAMPLE_PATH)/../../../libugba
UMOD_PLAYER := $(EXAMPLE_PATH)/../../../umod-player/player
UMOD_PACKER := $(EXAMPLE_PATH)/../../../build/umod-player/packer/umod_packer

include $(EXAMPLE_PATH)/../../common.mk
