# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 Antonio Niño Díaz

EXAMPLE_PATH := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

LIBUGBA := $(EXAMPLE_PATH)/../../../libugba

DEFINES := -DUGBA_DEBUG

include $(EXAMPLE_PATH)/../../common.mk
