# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 Antonio Niño Díaz

EXAMPLE_PATH := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

LIBGBALINE := $(EXAMPLE_PATH)/../../../libgbaline

include $(EXAMPLE_PATH)/../../common.mk
