// SPDX-License-Identifier: MIT
//
// Copyright (c) 2020 Antonio Niño Díaz

// Example of how to load 16-color sprites

#include <ugba/ugba.h>

#include "ball_green.h" // Autogenerated from ball_green.png
#include "ball_red.h"   // Autogenerated from ball_red.png

// This defines the tile index where the data of the ball is loaded in tile VRAM
#define BALL_RED_TILES_BASE         (16)
#define BALL_GREEN_TILES_BASE       (64)

// This is the palette index to be used for the sprite. There are 16 palettes of
// 16 colors each available.
#define BALL_RED_PALETTE            (2)
#define BALL_GREEN_PALETTE          (6)

int main(int argc, char *argv[])
{
    UGBA_Init(&argc, &argv);

    // Enable interrupts. This is needed for SWI_VBlankIntrWait() to work.
    IRQ_Enable(IRQ_VBLANK);

    // Set object attributes
    // ---------------------

    // Ball that rotates

    OBJ_AffineInit(0, 44, 64, OBJ_SIZE_32x32, 0,
                   0, BALL_RED_PALETTE, BALL_RED_TILES_BASE, 0);

    // Balls that grow and shrink. One with double size mode disabled, the other
    // one has it enabled.

    OBJ_AffineInit(1, 164, 8, OBJ_SIZE_32x32, 1,
                   0, BALL_GREEN_PALETTE, BALL_GREEN_TILES_BASE, 0);

    OBJ_AffineInit(2, 164, 88, OBJ_SIZE_32x32, 1,
                   0, BALL_GREEN_PALETTE, BALL_GREEN_TILES_BASE, 1);

    obj_affine_src_t objsrc_init[] =
    {
        { 1 << 8, 1 << 8, 0, 0 },
        { 1 << 8, 1 << 8, 0, 0 },
    };
    SWI_ObjAffineSet_OAM(&objsrc_init[0], MEM_OAM, 2);

    // Load the palettes
    // -----------------

    VRAM_OBJPalette16Copy(ball_redPal, ball_redPalLen,
                          BALL_RED_PALETTE);
    VRAM_OBJPalette16Copy(ball_greenPal, ball_greenPalLen,
                          BALL_GREEN_PALETTE);

    // Load the tiles
    // --------------

    VRAM_OBJTiles16Copy(ball_redTiles, ball_redTilesLen,
                        BALL_RED_TILES_BASE);
    VRAM_OBJTiles16Copy(ball_greenTiles, ball_greenTilesLen,
                        BALL_GREEN_TILES_BASE);

    // Turn on the screen
    // ------------------

    REG_DISPCNT =
        // The mode doesn't matter here, it only affects the backgrounds. This
        // is just an arbitrary value.
        DISPCNT_BG_MODE(0) |
        // Turn on the rendering of sprites.
        DISPCNT_OBJ_ENABLE |
        // Enable 1D mapping. Check "8.2.1. The sprite mapping mode" in the
        // following link for more information:
        //     https://www.coranac.com/tonc/text/regobj.htm#sec-tiles
        DISPCNT_OBJ_1D_MAPPING;

    uint16_t angle = 0x20;

    // Note that this is actually inverted. If you set the scale to 2.0, the
    // sprite will be scaled down to 0.5.
#define MIN_SCALE   ((1 << 8) / 2)
#define MAX_SCALE   ((1 << 8) * 2)
#define SPEED_SCALE (1 << 2)

    uint16_t scale = MIN_SCALE;
    uint16_t scale_v = SPEED_SCALE;

    while (1)
    {
        SWI_VBlankIntrWait();

        obj_affine_src_t objsrc[] =
        {
            { 1 << 8, 1 << 8, angle << 8, 0 },
            { scale, scale, 0, 0 },
        };
        SWI_ObjAffineSet_OAM(&objsrc[0], MEM_OAM, 2);

        angle++;

        scale += scale_v;

        if (scale < MIN_SCALE)
            scale_v = SPEED_SCALE;
        else if (scale > MAX_SCALE)
            scale_v = -SPEED_SCALE;
    }
}


