# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020-2021 Antonio Niño Díaz

EXAMPLE_PATH := $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

LIBUGBA := $(EXAMPLE_PATH)/../../../libugba

# Uncomment the following line to enable assertions
#DEFINES := -DUGBA_DEBUG

include $(EXAMPLE_PATH)/../../common.mk
