// SPDX-License-Identifier: MIT
//
// Copyright (c) 2020 Antonio Niño Díaz

// Example of how to load 256-color sprites

#include <ugba/ugba.h>

#include "ball.h" // Autogenerated from ball.png

// This defines the tile index where the data of the ball is loaded in tile VRAM
#define BALL_TILES_BASE         (16)

int main(int argc, char *argv[])
{
    UGBA_Init(&argc, &argv);

    // Enable interrupts. This is needed for SWI_VBlankIntrWait() to work.
    IRQ_Enable(IRQ_VBLANK);

    // Set object attributes
    // ---------------------

    OBJ_RegularInit(0, 32, 32, OBJ_SIZE_32x32,
                    OBJ_256_COLORS, 0, BALL_TILES_BASE);

    // Load the palettes
    // -----------------

    VRAM_OBJPalette256Copy(ballPal, ballPalLen);

    // Load the tiles
    // --------------

    VRAM_OBJTiles256Copy(ballTiles, ballTilesLen, BALL_TILES_BASE);

    // Turn on the screen
    // ------------------

    REG_DISPCNT =
        // The mode doesn't matter here, it only affects the backgrounds. This
        // is just an arbitrary value.
        DISPCNT_BG_MODE(0) |
        // Turn on the rendering of sprites.
        DISPCNT_OBJ_ENABLE |
        // Enable 1D mapping. Check "8.2.1. The sprite mapping mode" in the
        // following link for more information:
        //     https://www.coranac.com/tonc/text/regobj.htm#sec-tiles
        DISPCNT_OBJ_1D_MAPPING;

    while (1)
        SWI_VBlankIntrWait();
}
